[project]
name = "dgree720-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "ipykernel>=7.0.0",
    "opencv-python>=4.12.0.88",
    "streamlit>=1.50.0",
    "yt-dlp>=2025.9.26",
]
